### ISSUE TITLE
java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by HiranManjula** [edvin/fxlauncher#120]
java.lang.ClassNotFoundException: com.greencoding.MyApp
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at fxlauncher.AbstractLauncher.createApplicationEnvironment(AbstractLauncher.java:161)
	at fxlauncher.Launcher.lambda$start$0(Launcher.java:149)
	at java.lang.Thread.run(Thread.java:748)

here is my pom file. it is work fine when your demo project executed. but when I started new project to implement that above exception is throwing when running the application.

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.greencoding</groupId>
    <artifactId>MyApp</artifactId>
    <version>1.0.0</version>
    <packaging>jar</packaging>

    <name>MyApp</name>
    
    <dependencies>
        <dependency>
            <groupId>no.tornado</groupId>
            <artifactId>fxlauncher</artifactId>
            <version>1.0.16</version>
        </dependency>
    </dependencies>

    <properties>
        
        <app.filename>MyApp</app.filename>

        
        <app.mainClass>com.greencoding.MyApp</app.mainClass>

        
        <app.cacheDir>USERLIB/MyApp</app.cacheDir>

        
        <app.parameters>--myOption=myValue --myOtherOption=myOtherValue</app.parameters>

        
        <app.vendor>Green Coding</app.vendor>

        
        <app.version>2.0</app.version>

        
        <app.url>http://demo.example</app.url> 

        
        <app.deploy.target>edvin@demo.example:demo</app.deploy.target> 

        
        <app.dir>${project.build.directory}/app</app.dir>

        
        <app.installerdir>${project.build.directory}/installer</app.installerdir>

        
        <app.acceptDowngrade>false</app.acceptDowngrade>
        
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <organization>
        
        <name>Green Coding</name>
    </organization>

    <build>
        <plugins>
            
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>2.6</version>
                <configuration>
                    <outputDirectory>${app.dir}</outputDirectory>
                </configuration>
            </plugin>
            
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>2.10</version>
                <configuration>
                    <excludeScope>provided</excludeScope>
                    <outputDirectory>${app.dir}</outputDirectory>
                    <stripVersion>true</stripVersion>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>1.4.0</version>
                
                <executions>
                    <execution>
                        <id>create-manifest</id>
                        <phase>package</phase>
                        <goals>
                            <goal>java</goal>
                        </goals>
                        <configuration>
                            <mainClass>fxlauncher.CreateManifest</mainClass>
                            <arguments>
                                <argument>${app.url}</argument>
                                <argument>${app.mainClass}</argument>
                                <argument>${app.dir}</argument>
                                <argument>--cache-dir=${app.cacheDir}</argument>
                                <argument>--accept-downgrade=${app.acceptDowngrade}</argument>
                                <argument>--include-extensions=jpg</argument>
                                <argument>${app.parameters}</argument>
                            </arguments>
                        </configuration>
                    </execution>
                    
                    <execution>
                        <id>embed-manifest-in-launcher</id>
                        <phase>package</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>jar</executable>
                            <workingDirectory>${app.dir}</workingDirectory>
                            <arguments>
                                <argument>uf</argument>
                                <argument>fxlauncher.jar</argument>
                                <argument>app.xml</argument>
                            </arguments>
                        </configuration>
                    </execution>
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    <execution>
                        <id>installer</id>
                        <phase>install</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>javapackager</executable>

                            <arguments>
                                <argument>-deploy</argument>
                                <argument>-native</argument>
                                <argument>-outdir</argument>
                                <argument>${app.installerdir}</argument>
                                <argument>-outfile</argument>
                                <argument>${app.filename}</argument>
                                <argument>-srcdir</argument>
                                <argument>${app.dir}</argument>
                                <argument>-srcfiles</argument>
                                <argument>fxlauncher.jar</argument>
                                <argument>-appclass</argument>
                                <argument>fxlauncher.Launcher</argument>
                                <argument>-name</argument>
                                <argument>${project.name}</argument>
                                <argument>-title</argument>
                                <argument>${project.name}</argument>
                                <argument>-vendor</argument>
                                <argument>${app.vendor}</argument>
                                <argument>-BappVersion=${app.version}</argument>
                                <argument>-Bidentifier=${project.groupId}.${project.artifactId}</argument>
                            </arguments>
                        </configuration>
                    </execution>
                    
                    <execution>
                        <id>deploy-app</id>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>scp</executable>
                            <arguments>
                                <argument>-r</argument>
                                <argument>target/app/.</argument>
                                <argument>${app.deploy.target}</argument>
                            </arguments>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.3</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>

**Comment by edvin** [comment]
The issue is that you don't have a class called `com.greencoding.MyApp` in your `target` folder. Double check the class name and inspect the target folder :) If not, can you post a link to your project so I can take a look at the code?

**Comment by HiranManjula** [comment]
okay, can you specify me where is the target folder is?

**Comment by edvin** [comment]
Directly in your project folder after you have built the project.

**Comment by HiranManjula** [comment]
yeah inside the target folder there are 5 folders.

![image](https://user-images.githubusercontent.com/11808329/40702140-44f6befa-63fe-11e8-975b-077845d97c93.png)

**Comment by HiranManjula** [comment]
My testing project link

https://github.com/HiranManjula/green-myapp

**Comment by HiranManjula** [comment]
hi edvin, could you please help me to get rid this out?

**Comment by edvin** [comment]
The reason is simple - the installer is now able to download the files from the url you provided (http://demo.example is not where you're hosting your application artifacts). Since the installer cannot download the application library files, it simply can't run the app. You posted the bottom most error message, but you'll see an error message pertaining to failed HTTP downloads higher up in the log. Before you try to run your app, you need to actually deploy the app files and make sure they are available at the url you specified.
