### ISSUE TITLE
App is not starting. Certification error.

### ISSUE THREAD

**Issue by Mistral** [edvin/fxlauncher#138]
Hello,

I'm using newest version of fxlauncher. I'm getting errors during app start (Error during File Synchronization phase):

```
Caused by: sun.security.validator.ValidatorException: No trusted certificate found
	at sun.security.validator.SimpleValidator.buildTrustedChain(SimpleValidator.java:397)
	at sun.security.validator.SimpleValidator.engineValidate(SimpleValidator.java:134)
	at sun.security.validator.Validator.validate(Validator.java:262)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1596)
	... 16 more
```

**Comment by edvin** [comment]
It seems like you have specified an https URL with either no valid certificate, or a certificate not accepted by the trust store in your Java installation.

**Comment by Mistral** [comment]
Ok thanks, it's working now.

**Comment by edvin** [comment]
Great, thanks for reporting back :)
