### ISSUE TITLE
fxlauncher does not seem to download all jar

### ISSUE THREAD

**Issue by ronsmits** [edvin/fxlauncher#26]
I can give you access to the code if you want, as this code is not public (yet)

````
ron@frankenstein ~/src/keepassjava $ java -jar target/app/fxlauncher.jar 
Sep 17, 2016 10:24:06 AM fxlauncher.Launcher lambda$start$0
INFO: Using cache dir /tmp
Sep 17, 2016 10:24:06 AM fxlauncher.Launcher lambda$start$0
WARNING: Error during File Synchronization phase
java.io.FileNotFoundException: http://ronsmits.org/ron/slf4j-simple.jar
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1836)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
        at java.net.URL.openStream(URL.java:1045)
        at fxlauncher.Launcher.syncFiles(Launcher.java:146)
        at fxlauncher.Launcher.lambda$start$0(Launcher.java:64)
        at java.lang.Thread.run(Thread.java:745)

Sep 17, 2016 10:24:06 AM fxlauncher.Launcher reportError
WARNING: Error during Create Application phase
java.lang.ClassNotFoundException: org.ronsmits.keepassswing.KeepassJava
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at fxlauncher.Launcher.createApplication(Launcher.java:171)
        at fxlauncher.Launcher.lambda$start$0(Launcher.java:70)
        at java.lang.Thread.run(Thread.java:745)

ron@frankenstein ~/src/keepassjava $ 
````

**Comment by edvin** [comment]
The file in question is not found, as the error message indicates :) Something went wrong with your deployment or you deployed to another location perhaps?

**Comment by ronsmits** [comment]
After cleaning the directory on the server and re uploading everything started working
