### ISSUE TITLE
Running demo installer results in a stacktrace

### ISSUE THREAD

**Issue by ChrisLMerrill** [edvin/fxlauncher#36]
Downloaded and ran the demo installer on Windows 10. Result is:

java.lang.NullPointerException
	at no.tornado.FxlDemo.start(FxlDemo.java:31)
	at fxlauncher.Launcher.lambda$launchAppFromManifest$2(Launcher.java:104)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)

**Comment by edvin** [comment]
Thanks, I have fixed the Windows installer now, will fix the Mac and Linux installers shortly. Can you confirm it is working for you now? You need to uninstall the old and download/reinstall.

The reason for the error is that I changed the FXLauncher version in the deployment, but didn't update the installer. There were some major changes a few versions back, so the installer also needed updating.

**Comment by edvin** [comment]
Linux installer updated as well, only Mac installer left.

**Comment by ChrisLMerrill** [comment]
Yes, that works now. Thanks!

**Comment by edvin** [comment]
Thanks for reporting it :) Mac installer is also updated.
