### ISSUE TITLE
Class not found exception 

### ISSUE THREAD

**Issue by aabhaanjan** [edvin/fxlauncher#93]
Hi 
In my system it is working fine when trying to install in other system it is throwing error:
Error during create application phase 
java.lang.ClassNotFoundException: com.lab.Main
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at fxlauncher.Launcher.createApplication(Launcher.java:179)
at fxlauncher.Launcher.lambda$start$0(Launcher.java:85)
at java.lang.Thread.run(Thread.java:745)

**Comment by aabhaanjan** [comment]
No base JDK. Package will use system JRE.
No base JDK. Package will use system JRE.
Creating app bundle: BurnAndTurn in C:\Users\project1\target\installer\bundles
Result application bundle: C:\Users\project1\target\installer\bundles
Installer (.exe) saved to: C:\Users\project1\\target\installer\bundles
Bundler MSI Installer skipped because of a configuration problem: Can not find WiX tools (light.exe, candle.exe).  
Advice to fix:   Download WiX 3.0 or later from http://wix.sf.net and add it to the PATH.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS

**Comment by aabhaanjan** [comment]
is this an error of jdk ?

**Comment by edvin** [comment]
The javapackager tool is telling you that you need to install WiX or InnoSetup before you're able to create installers :) http://www.jrsoftware.org/isinfo.php

**Comment by aabhaanjan** [comment]
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>Sample</groupId>
  <artifactId>Sample</artifactId>
  <version>4.0.7</version>
    <properties>

         
    
    <app.filename>${project.name}</app.filename>

    
    <app.mainClass>com.abc.Main</app.mainClass>

    
    <app.dir>${project.build.directory}/app</app.dir>

    
    <app.installerdir>${project.build.directory}/installer</app.installerdir>

    
    <app.url>http://www.abc.com/game/</app.url>
     <app.acceptDowngrade>false</app.acceptDowngrade>
     <app.icon>src/main/deploy/package/windows/Sample.ico</app.icon>

    


    </properties>


    <build>
        <sourceDirectory>src</sourceDirectory>
        <plugins>
         
                       <plugin>
                           <groupId>org.apache.maven.plugins</groupId>
                           <artifactId>maven-jar-plugin</artifactId>
                           <version>2.6</version>
                           <configuration>
                               <outputDirectory>${app.dir}</outputDirectory>
                          </configuration>
                       </plugin>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.3</version>
        <configuration>
        <compilerArguments>
        	<endorseddirs>${basedir}/src/main/resources/sfs</endorseddirs>
		  </compilerArguments>
		          <source>1.8</source>
		          <target>1.8</target>
		          <mainClass>com.abc.Main</mainClass>
		        </configuration>
      </plugin>

         <plugin>
          <groupId>com.zenjava</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>8.1.2</version>
                <configuration>
                <appName>Sample</appName>
        		<title>Sample</title>
        		<description>Sample-sample</description>
        		<vendor>example</vendor>
                    <mainClass>com.abc.Main</mainClass>
                    <verbose>true</verbose>
                     <bundler>EXE</bundler>
			        <bundleArguments>
			                <icon.ico>src/main/deploy/package/windows/Sample.ico</icon.ico>
            				<icon.png>src/main/deploy/package/windows/Sample.png</icon.png>
			        </bundleArguments>
			        <needShortcut>true</needShortcut>
			         <additionalAppResources>src/main/deploy/package/windows</additionalAppResources>

                </configuration>

            </plugin>
            <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <version>2.10</version>
        <executions>
          <execution>
            <id>copy-dependencies</id>
            <phase>package</phase>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <configuration>
                    <outputDirectory>${app.dir}</outputDirectory>
              <overWriteReleases>false</overWriteReleases>
              <overWriteSnapshots>false</overWriteSnapshots>
              <overWriteIfNewer>true</overWriteIfNewer>
            </configuration>
          </execution>
        </executions>
      </plugin>


            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>1.4.0</version>
                
                <executions>
                    <execution>
                        <id>create-manifest</id>
                        <phase>package</phase>
                        <goals>
                            <goal>java</goal>
                        </goals>
                        <configuration>
                            <mainClass>fxlauncher.CreateManifest</mainClass>
                            <arguments>
                                <argument>${app.url}</argument>
                                <argument>${app.mainClass}</argument>
                                <argument>${app.dir}</argument>
                                <argument>--cache-dir=${app.cacheDir}</argument>
                                <argument>--accept-downgrade=${app.acceptDowngrade}</argument>
                                <argument>${app.parameters}</argument>
                            </arguments>
                        </configuration>
                    </execution>
                    
                  <execution>
                        <id>embed-manifest-in-launcher</id>
                        <phase>package</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>jar</executable>
                            <workingDirectory>${app.dir}</workingDirectory>
                            <arguments>
                                <argument>uf</argument>
                                <argument>fxlauncher-1.0.13.jar</argument>
                                <argument>app.xml</argument>
                            </arguments>
                        </configuration>
                    </execution>
                    
                    
                        
                        
                        
                            
                        
                        
                            
                            
                            
                                
                                
                                
                                
                                
                            
                        
                    
                    
                    <execution>
                        <id>installer</id>
                        <phase>install</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>javapackager</executable>

                            <arguments>
                                <argument>-deploy</argument>
                                <argument>-native</argument>
                                <argument>-outdir</argument>
                                <argument>${app.installerdir}</argument>
                                <argument>-outfile</argument>
                                <argument>${app.filename}</argument>
                                <argument>-srcdir</argument>
                                <argument>${app.dir}</argument>
                                <argument>-srcfiles</argument>
                                <argument>fxlauncher-1.0.13.jar</argument>
                                <argument>-appclass</argument>
                                <argument>fxlauncher.Launcher</argument>
                                <argument>-name</argument>
                                <argument>${project.name}</argument>
                                <argument>-title</argument>
                                <argument>${project.name}</argument>
                                <argument>-vendor</argument>
                                <argument>${app.vendor}</argument>
                                <argument>${app.version}</argument>
                                <argument>${project.groupId}.${project.artifactId}</argument>
                                <argument>-Bicon=Sample.ico</argument>
                                <argument>-BSetupIconFile=src\main\deploy\package\windows\Sample-setup-icon.bmp</argument>
                                <argument>-BshortcutHint=true</argument>
                                 


                            </arguments>
                        </configuration>
                    </execution>
                    
                    <execution>
                        <id>deploy-app</id>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>scp</executable>
                            <arguments>
                                <argument>-r</argument>
                                <argument>${app.dir}/.</argument>
                                <argument>${app.deploy.target}</argument>
                            </arguments>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
    </plugins>


  </build>
<dependencies>
		<dependency>
            <groupId>smartfox</groupId>
            <artifactId>sfs2x-api</artifactId>
            <version>1.0.1</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>smartfox</groupId>
            <artifactId>sfs2x-client-core</artifactId>
            <version>1.0.1</version>
             <scope>compile</scope>
        </dependency>

		<dependency>
            <groupId>smartfox</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.0.1</version>
        </dependency>

		<dependency>
        	<groupId>smartfox</groupId>
        	<artifactId>slf4j-simple</artifactId>
        	<version>1.0.1</version>
        </dependency>
        
		<dependency>
		    <groupId>org.slf4j</groupId>
		    <artifactId>slf4j-api</artifactId>
		    <version>1.6.4</version>
		    <scope>compile</scope>
		</dependency>

		
		
		<dependency>
		    <groupId>org.slf4j</groupId>
		    <artifactId>jcl-over-slf4j</artifactId>
		    <version>1.6.4</version>
		    <scope>runtime</scope>
		</dependency>

		
		
		<dependency>
		    <groupId>org.slf4j</groupId>
		    <artifactId>slf4j-log4j12</artifactId>
		    <version>1.6.4</version>
		    <scope>runtime</scope>
		</dependency>

		
		
		<dependency>
		    <groupId>log4j</groupId>
		    <artifactId>log4j</artifactId>
		    <version>1.2.16</version>
		</dependency>
		<dependency>
		    <groupId>smartfox</groupId>
		    <artifactId>netty</artifactId>
		    <version>1.0.1</version>
		</dependency>
        <dependency>
			  <groupId>javafx</groupId>
			  <artifactId>jfxrt</artifactId>
			  <version>${java.version}</version>
			  <scope>system</scope>
			  <systemPath>${java.home}/lib/ext/jfxrt.jar</systemPath>
		</dependency>

 		<dependency>
		    <groupId>fxlauncher</groupId>
             <artifactId>fxlauncher</artifactId>
		    <version>1.0.13</version>
		</dependency>
  </dependencies>


</project>

**Comment by edvin** [comment]
I can't see anything immediately wrong here, can you also provide the installer?

**Comment by FranAguiar** [comment]
I'm getting this error too. productionApp jar and fxlauncher.jar are in the same folder (target/app) with al the dependencies

> Error during Create Application phase
> java.lang.ClassNotFoundException: com.project.clients.production.ProductionApp
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	at fxlauncher.AbstractLauncher.createApplicationEnvironment(AbstractLauncher.java:170)
> 	at fxlauncher.Launcher.lambda$start$0(Launcher.java:149)
> 	at java.lang.Thread.run(Thread.java:748)

**Comment by jperezcu** [comment]
Same problem here, this started happening less than a month ago.

**Comment by jperezcu** [comment]
Hi @edvin, I'm getting the same error as well using the OSX installer found here: https://tix.innova-red.net/downloads/assets/tix-time-client-0.1.0-SNAPSHOT.dmg

`java.lang.ClassNotFoundException: com.github.tix_measurements.time.client.Main
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at fxlauncher.AbstractLauncher.createApplicationEnvironment(AbstractLauncher.java:170)
	at fxlauncher.Launcher.lambda$start$0(Launcher.java:149)
	at java.lang.Thread.run(Thread.java:745)
`
Here's the repo: [tix-time-client](https://github.com/jperezcu/tix-time-client)

**Comment by edvin** [comment]
Before this error you should have gotten another error which will most probably show you what the real issue is :) Can you post the complete output if you run the app from the command line?

**Comment by jperezcu** [comment]
I forgot to add, this error appears inside an error window only when executing the .app file, NOT when executing .jar file (using the jar works perfectly). And the error window starts with "Error during Create Application phase".

**Comment by edvin** [comment]
I don't have a Mac atm, but I cloned the tix-time-client repo and did `gradle generateNativeInstaller` and then ran the installer exe. It installed the app perfectly and started it without issues. Is the issue only Mac specific perhaps?

**Comment by jperezcu** [comment]
Yes, it's definitely Mac specific.
